package com.dragonguard.backend.support.batch;

import com.dragonguard.backend.domain.gitrepo.entity.GitRepo;

import java.util.List;

public abstract class GitRepoBatchTest {
    protected List<GitRepo> gitRepos =  List.of(
            GitRepo.builder().name("tukcom2023CD/DragonGuard-JinJin").build(),
            GitRepo.builder().name("tukcom2023CD/BoSS").build(),
            GitRepo.builder().name("tukcom2023CD/GoldenClinic").build(),
            GitRepo.builder().name("tukcom2023CD/MBTI").build(),
            GitRepo.builder().name("tukcom2023CD/RISING").build(),
            GitRepo.builder().name("tukcom2023CD/MYWAY").build(),
            GitRepo.builder().name("tukcom2023CD/AOK").build(),
            GitRepo.builder().name("ohksj77/DragonGuard-JinJin").build(),
            GitRepo.builder().name("ohksj77/ohksj77").build(),
            GitRepo.builder().name("ohksj77/DragonGuard-JinJin-API-Docs").build(),
            GitRepo.builder().name("ohksj77/kotlin-spring-batch").build(),
            GitRepo.builder().name("ohksj77/Sammuelwoojae").build(),
            GitRepo.builder().name("ohksj77/used-car").build(),
            GitRepo.builder().name("ohksj77/Algorithm_java").build(),
            GitRepo.builder().name("ohksj77/DoodleDoodle-v2").build(),
            GitRepo.builder().name("ohksj77/jenkins-docker").build(),
            GitRepo.builder().name("ohksj77/server-mentoring").build(),
            GitRepo.builder().name("ohksj77/tino-bus").build(),
            GitRepo.builder().name("ohksj77/spring-mentoring").build(),
            GitRepo.builder().name("ohksj77/Algorithm_py").build(),
            GitRepo.builder().name("ohksj77/owl-forest").build(),
            GitRepo.builder().name("ohksj77/kubernetes-demo").build(),
            GitRepo.builder().name("ohksj77/spring-security").build(),
            GitRepo.builder().name("ohksj77/MySNS").build(),
            GitRepo.builder().name("ohksj77/flutter_sns").build(),
            GitRepo.builder().name("ohksj77/jpashop").build(),
            GitRepo.builder().name("ohksj77/DoodleDoodle").build(),
            GitRepo.builder().name("ohksj77/bidbid").build(),
            GitRepo.builder().name("ohksj77/AlgorithmReview").build(),
            GitRepo.builder().name("ohksj77/Coupowning_Store").build(),
            GitRepo.builder().name("ohksj77/PlanYourDay").build(),
            GitRepo.builder().name("ohksj77/html_css_clone_coding").build(),
            GitRepo.builder().name("ohksj77/msa-config-repo").build(),
            GitRepo.builder().name("ohksj77/algorithm_challenge").build(),
            GitRepo.builder().name("ohksj77/Cocktail_spring").build(),
            GitRepo.builder().name("ohksj77/ksj369").build(),
            GitRepo.builder().name("ohksj77/ModernJava").build(),
            GitRepo.builder().name("ohksj77/seungjin-spring-gg").build(),
            GitRepo.builder().name("ohksj77/.github").build(),
            GitRepo.builder().name("ohksj77/DockerStudy").build(),
            GitRepo.builder().name("ohksj77/core_spring").build(),
            GitRepo.builder().name("ohksj77/SimriTest").build(),
            GitRepo.builder().name("ohksj77/MarioGame").build(),
            GitRepo.builder().name("ohksj77/InflearnSpring").build(),
            GitRepo.builder().name("ohksj77/Spring5").build(),
            GitRepo.builder().name("ohksj77/Algorithm_c").build(),
            GitRepo.builder().name("ohksj77/TicketBox").build());
}
