:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4


== Member 멤버
=== 멤버 생성
operation::create member[snippets='http-request,http-response']

=== 멤버 티어 조회
operation::get member tier[snippets='http-request,http-response']

=== 멤버 커밋 내역 업데이트
operation::update member contributions[snippets='http-request,http-response']

=== 멤버 전체 랭킹 조회
operation::get member ranking[snippets='http-request,http-response']

=== 멤버 지갑 주소 갱신
operation::update member wallet[snippets='http-request,http-response']

=== 조직 내부 멤버 랭킹
operation::get member ranking in a organization[snippets='http-request,http-response']

=== 멤버 Jwt 토큰으로 조회
operation::get member by jwt[snippets='http-request,http-response']

=== 멤버 github 조직 및 레포 목록 조회
operation::get member details[snippets='http-request,http-response']

=== 멤버 블록체인 업데이트
operation::update member blockchains[snippets='http-request,http-response']

=== 멤버 github 조직의 레포 목록 조회
operation::get member repositories in a organization[snippets='http-request,http-response']

=== 타 멤버의 프로필 조회
operation::get other member details[snippets='http-request,http-response']
